### ISSUE TITLE
Plugin returns error: gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by jvangrouw** [helm/helm-mapkubeapis#104]
Since this morning our builds are failing. The tar.gz seems not to exist?

Downloading and installing helm-mapkubeapis v0.4.1 ...
https://github.com/helm/helm-mapkubeapis/releases/download/v0.4.1/helm-mapkubeapis_0.4.1_linux_amd64.tar.gz
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: plugin install hook for "mapkubeapis" exited with error

We install the plugin via:

helm plugin install https://github.com/helm/helm-mapkubeapis

**Comment by hickeyma** [comment]
Its only being built. Wait until its available.

**Comment by hickeyma** [comment]
Its should be available now.

**Comment by jvangrouw** [comment]
That was it indeed, builds are working again! Thanks!
