### ISSUE TITLE
issues executing with "oidc" auth provider 

### ISSUE THREAD

**Issue by treestructure** [helm/helm-mapkubeapis#129]
Auth pro

2023/12/04 16:04:10 Release 'wp3-ms-dep' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2023/12/04 16:04:10 Get release 'wp3-ms-dep' latest version.
Error: failed to get release 'wp3-ms-dep' latest version: query: failed to query with labels: no Auth Provider found for name "oidc"
Error: plugin "mapkubeapis" exited with erro

**Comment by yuzhouliu9** [comment]
duplicate of https://github.com/helm/helm-mapkubeapis/issues/113

Unmerged fix here: https://github.com/helm/helm-mapkubeapis/pull/115

**Comment by hickeyma** [comment]
Closing as duplicate of #113
