### ISSUE TITLE
State of this project?

### ISSUE THREAD

**Issue by Nexarian** [helm/helm-mapkubeapis#131]
The last update was made nearly a year ago. There are multiple open PRs that are many months old and have received little-to-no-attention. Meanwhile this plugin is the plan of record for how to unblock very difficult helm upgrade issues.

Is this project still active and/or can it be handed off to a new owner?

**Comment by robertsirc** [comment]
It is still going is there a particular issue you are referencing?

**Comment by mattfarina** [comment]
@Nexarian it's still maintained but the activity comes in spikes. There should be some activity in the near future.

**Comment by Nexarian** [comment]
Good to know, thanks.

**Comment by mattfarina** [comment]
Closing this issue as, I think, the question has been answered.
