### ISSUE TITLE
Forgot to update plugin.yaml version before releasing 0.5.0?

### ISSUE THREAD

**Issue by joshsleeper** [helm/helm-mapkubeapis#169]
tl;dr `helm plugin install` for this project is currently installing `0.4.1` instead of the recently released `0.5.0`.

looking at the debug output from the install command it appears to be because of the version string it's parsing from `plugin.yaml`, which is still `0.4.1` there.

<https://github.com/helm/helm-mapkubeapis/blob/6a5bc4bb29c07c9f6dce366b4d9af27f8b9daa15/plugin.yaml#L2>

Output of `helm version`:

```
version.BuildInfo{Version:"v3.15.3", GitCommit:"3bb50bbbdd9c946ba9989fbe4fb4104766302a64", GitTreeState:"clean", GoVersion:"go1.22.5"}
```

Output of `helm plugin install https://github.com/helm/helm-mapkubeapis --debug`

```
[debug] vcs_installer.go:159: cloning https://github.com/helm/helm-mapkubeapis to /home/jsleeper/.cache/helm/plugins/https-github.com-helm-helm-mapkubeapis
[debug] vcs_installer.go:91: copying /home/jsleeper/.cache/helm/plugins/https-github.com-helm-helm-mapkubeapis to /home/jsleeper/.local/share/helm/plugins/helm-mapkubeapis
plugin_install.go:82: [debug] loading plugin from /home/jsleeper/.local/share/helm/plugins/helm-mapkubeapis
plugin.go:60: [debug] running install hook: /usr/bin/sh -c cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh
Downloading and installing helm-mapkubeapis v0.4.1 ...
https://github.com/helm/helm-mapkubeapis/releases/download/v0.4.1/helm-mapkubeapis_0.4.1_linux_amd64.tar.gz
Installed plugin: mapkubeapis
```

**Comment by robertsirc** [comment]
Thanks for letting me know I can get this fixed right away.

**Comment by mattfarina** [comment]
v0.5.1 is building now with this fix. Closing the issue.

**Comment by joshsleeper** [comment]
nice, thanks gang I we appreciate it!
