### ISSUE TITLE
No deprecated apiVersions found when generated manifest has `kind` and `apiVersion` in a different order

### ISSUE THREAD

**Issue by agaffney** [helm/helm-mapkubeapis#46]
I came across a helm chart that generated manifests such as the following:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
```

Because the mapping file is using a multiline substring match that looks for `apiVersion` followed by `kind`, the tool did not recognize these resources as needing to be updated. I had to manually edit the map file to switch the order to get it to work.

**Comment by hickeyma** [comment]
@agaffney That is the reason for the mapping file being configurable. It can be used to match different formats. See https://github.com/hickeyma/helm-mapkubeapis#api-mapping for more details.

**Comment by agaffney** [comment]
I created a custom map file to work around it, but the fact that it didn't find anything when I first ran it was very confusing.

**Comment by hickeyma** [comment]
@agaffney That is a good point. Would you like to push a PR to improve the README?
