### ISSUE TITLE
Question: Removal of Helm v2 support?

### ISSUE THREAD

**Issue by hickeyma** [helm/helm-mapkubeapis#50]
Helm [v2.17.0](https://github.com/helm/helm/releases/tag/v2.17.0) was the final release of Helm v2 in October 2020. Helm v2 is unsupported since November 2020, as detailed in [Helm 2 and the Charts Project Are Now Unsupported](https://helm.sh/blog/helm-2-becomes-unsupported/).

Helm v2 uses an older version of Kubernetes Go client which is incompatible with Kubernetes Go Client 1.18+. [helm-mapkubeapis](https://github.com/helm/helm-mapkubeapis) calls Helm v2 storage APIs which in turn call Kubernetes Go client APIs. This means that the plugin is restricted to using Helm [v3.1.3](https://github.com/helm/helm/releases/tag/v3.1.3) (last Helm v3 release which uses Kubernetes Go Client pre 1.18) which was released in April 2020.

Is it time to drop support for Helm v2 in this plugin as Helm v2 is no longer supported? The benefit is that we can update to the latest dependencies.

**Comment by marckhouzam** [comment]
I agree support for v2 should be dropped.

The plugin even has older versions tagged oif anyone needs to use it with v2 and an old kubernetes.

I think it is important for this plugin to keep up with the latest helm versions.

Thanks @hickeyma for bringing this up.

**Comment by mattfarina** [comment]
I agree, this is a fine time to remove v2 support. If someone needs it they can get an older version of the plugin.

**Comment by jdolitsky** [comment]
I am OK with this

**Comment by scottrigby** [comment]
I support this as well, agree with Marc and Matt's reasons above. 

@hickeyma quick question, are you thinking we’ll also drop support for https://github.com/helm/helm-2to3, or in “Recommended Prior to Migration (https://github.com/helm/helm-2to3#recommended-prior-to-migration)” suggest an alternative approach to mapkubeapis plugin?

**Comment by hickeyma** [comment]
> quick question, are you thinking we’ll also drop support for https://github.com/helm/helm-2to3, or in “Recommended Prior to Migration ([https://github.com/helm/helm-2to3#recommended-prior-to-migration)”](https://github.com/helm/helm-2to3#recommended-prior-to-migration)%E2%80%9D) suggest an alternative approach to mapkubeapis plugin?

No, not stopping support yet for  https://github.com/helm/helm-2to3 as folks are possibly still migrating or even using Helm v2. If someone needs the [mapkubeapis](https://github.com/helm/helm-mapkubeapis) Helm v2 capability, they can use [release v0.2.0](https://github.com/helm/helm-mapkubeapis/releases/tag/v0.2.0) of the plugin.

**Comment by hickeyma** [comment]
Thanks @mattfarina @jdolitsky @marckhouzam @scottrigby for the feedback.
