### ISSUE TITLE
Add deprecated "HorizontalPodAutoscaler" apiversion

### ISSUE THREAD

**Issue by hydeenoble** [helm/helm-mapkubeapis#67]
Using this plugin and I noticed that there is no specification for the `HorizontalPodAutoscaler` resource as specified in the [Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/). I would love to create a PR for this.

**Comment by hickeyma** [comment]
@hydeenoble Go for it.

**Comment by hydeenoble** [comment]
Awesome!
