### ISSUE TITLE
Darwin arm64?

### ISSUE THREAD

**Issue by Noksa** [helm/helm-mapkubeapis#70]
Hello.

Do you have a plan to support native binary for Apple Silicon M1?

**Comment by hickeyma** [comment]
@Noksa is this Darwin ARM64?

**Comment by Noksa** [comment]
I mean there is no compiled binary for darwin arm64
https://github.com/helm/helm-mapkubeapis/releases/tag/v0.3.0

so when I install the plugin on Mac M1 it is installed for arm64 and uses Rosetta emulation.

**Comment by hickeyma** [comment]
@Noksa Do you want to investigate the correct binary build and push the changes? The build details are [here](https://github.com/helm/helm-mapkubeapis/blob/main/.goreleaser.yml#L1-L12).

**Comment by mattfarina** [comment]
The next release will handle this. The change was merged. Closing the issue.
