### ISSUE TITLE
Failing on plugin installation 

### ISSUE THREAD

**Issue by priyadesai23** [helm/helm-mapkubeapis#72]
getting error like below 

Helm 3.7.1 and 3.8.1 used but same issue 

./linux-amd64/helm plugin install https://github.com/helm/helm-mapkubeapis
Downloading and installing helm-mapkubeapis v0.3.0 ...
https://github.com/helm/helm-mapkubeapis/releases/download/v0.3.0/helm-mapkubeapis_0.3.0_linux_amd64.tar.gz

**gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: plugin install hook for "mapkubeapis" exited with error**

**Comment by hickeyma** [comment]
@priyadesai23 I am unable to reproduce the error. I installed the plugin on Ubuntu as follows:

```console
$ helm plugin install https://github.com/helm/helm-mapkubeapis

Downloading and installing helm-mapkubeapis v0.3.0 ...
https://github.com/helm/helm-mapkubeapis/releases/download/v0.3.0/helm-mapkubeapis_0.3.0_linux_amd64.tar.gz
Installed plugin: mapkubeapis

$ helm plugin list
NAME       	VERSION	DESCRIPTION                                                               
2to3       	0.7.0  	migrate and cleanup Helm v2 configuration and releases in-place to Helm v3
diff       	3.1.3  	Preview helm upgrade changes as a diff                                    
mapkubeapis	0.3.0  	Map release deprecated Kubernetes APIs in-place 
```

Would you be able to provide more details to help troubleshoot the issue?

**Comment by vzabawski** [comment]
I have a similar issue while installing the plugin on WSL.
```
helm plugin install https://github.com/helm/helm-mapkubeapis
Downloading and installing helm-mapkubeapis v0.3.2 ...
https://github.com/helm/helm-mapkubeapis/releases/download/v0.3.2/helm-mapkubeapis_0.3.2_linux_amd64.tar.gz
/usr/bin/gzip: 1: ELF: not found
/usr/bin/gzip: 3: : not found
/usr/bin/gzip: 4: Syntax error: "(" unexpected
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: plugin install hook for "mapkubeapis" exited with error
```

**Comment by hickeyma** [comment]
Ping @priyadesai23

**Comment by hickeyma** [comment]
Closing as no response from OP.
