### ISSUE TITLE
Offline installation of helm plugin.

### ISSUE THREAD

**Issue by khayalghosh** [helm/helm-mapkubeapis#76]
Hey,

Is there a way we can do offline installation of the helm-mapkubeapis plugin without hitting internet.
I did try to modify the install_plugin.sh script with my internal repo and pushed helm-mapkubeapis_0.3.0_linux_amd64.tar.gz to my local repo but the installation is not successful.

**Comment by drewgonzales360** [comment]
I don't know if I can help much without seeing the environment, but maybe taking a look at the [helm plugin](https://helm.sh/docs/topics/plugins/#installing-a-plugin) docs will help. Maybe the $HELM_PLUGINS isn't set?

**Comment by pgier** [comment]
@khayalghosh  If you have the sources in a local directory, you can install directly from your local build.
https://github.com/helm/helm-mapkubeapis#developer-from-source-install

**Comment by hickeyma** [comment]
@khayalghosh Does the response by @pgier in https://github.com/helm/helm-mapkubeapis/issues/76#issuecomment-1213289942 answer your question?

**Comment by khayalghosh** [comment]
I agree we should extract tarball at HELM_PLUGIN location did worked!
