### ISSUE TITLE
Passing tls and tiller-namespace?

### ISSUE THREAD

**Issue by winrono** [helm/helm-mapkubeapis#81]
I'm trying to use 0.2.0 version of this plugin with Helm 2 version. Helm is configured with tls and tiller is deployed in separate namespace, therefore, I have to use --tls and --tiller-namespace flags.

Trying to run `helm mapkubeapis prometheus-operator --namespace monitoring --dry-run --tls --tiler-namespace=tiller` but it doesn't work (throwing error about this additional flags)

**Comment by hickeyma** [comment]
@winrono Support for v2 is now end of support. Helm v2 went [end of support](https://helm.sh/blog/helm-2-becomes-unsupported/) in November 2020. I suggest migrating to Helm 3.

**Comment by hickeyma** [comment]
@winrono I suggest reading then [Usage](https://github.com/helm/helm-mapkubeapis/tree/release-0.2#usage) as the following flags are not valid: `-tls --tiler-namespace`. 

You would need to pass `--v2` and `--namespace` should be the tiller namespace.

**Comment by winrono** [comment]
@hickeyma thanks for the answer. As we migrated to Helm 3 this question isn't relevant anymore
