### ISSUE TITLE
Allow removal of resources for APIs that do not exist anymore

### ISSUE THREAD

**Issue by stormqueen1990** [helm/helm-mapkubeapis#85]
I was experimenting with `helm-mapkubeapis` and noticed that it currently does not offer a way of removing resources. However, in the case of the PodSecurityPolicy API, there is no new version to apply. It would be useful to have logic to allow removals when applicable.

**Comment by hickeyma** [comment]
@stormqueen1990 Thanks for taking this on and pushing a PR.

**Comment by hickeyma** [comment]
Closed by #95
